language: cpp
dist: trusty

branches:
  only:
    dev
    master
    
before_install:
  - CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  - cmake --version
  - ASTYLE_URL="https://github.com/Bareflank/astyle/archive/master.zip"
  - travis_retry wget --quiet ${ASTYLE_URL}
  - unzip master.zip
  - cd astyle-master/build/clang && make
  - export PATH="${TRAVIS_BUILD_DIR}/astyle-master/build/clang/bin:${PATH}"

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build

matrix:
  include:

  - os: linux
    env:
      - TEST="G++ 7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    script:
      - cmake -DCMAKE_CXX_COMPILER="g++-7" ..
      - make
      - make test

  - os: linux
    env:
      - TEST="Clang 5.0"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    script:
      - cmake -DCMAKE_CXX_COMPILER=clang++-5.0 ..
      - make
      - make test

  - os: linux
    env:
      - TEST="Git DiffCheck"
    script:
      - |
        if [[ -n $(git diff --check HEAD^) ]]; then
          echo "You must remove whitespace before submitting a pull request"
          echo ""
          git diff --check HEAD^
          exit -1
        fi

  - os: linux
    env:
      - TEST="Astyle Format"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    script:
      - cmake ..
      - make format
      - |
        if [[ -n $(git diff) ]]; then
          echo "You must run make format before submitting a pull request"
          echo ""
          git diff
          exit -1
        fi
